/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react'
import getToken from './api/spotifyAPI.js'
import Image from 'next/image.js'
const logo = require('../public/logo_transparent.png');
const videoBg = require('/public/production ID_4990245.gif');

export default function Home() {
  
  const [ darkMode, setDarkmode] = useState(true);
  
  //getToken.execute();

  return (
    <div className={darkMode ? "dark" : "light"}>
      <Head>
        <title>DXVIL デビル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dxvil.ico" />
      </Head>

      <main className='bg-transparent '>
        <section className='min-h-screen px-10 backdrop-blur-xl'>
          <nav className='py-10 mb-12 flex justify-between text-red-400'>
            <div className='cursor-pointer select-none flex justify-around'>
              <Image src={logo} width={50} height={50}></Image>
              <h1 className='text-2xl  font-benzin text-red-400 ml-3 self-center'>DXVIL <span className='font-gothic'>デビル</span></h1>
            </div>
            <ul className='flex justify-around w-5/12 self-center flex-'>
              <li>
                <a className='font-benzin'>MUSIC</a>
              </li>
              <li className='hidden'>
                <a className='font-benzin'>MERCH</a>
              </li>
              <li>
                <a className='font-benzin'>CODE</a>
              </li>
              <li>
                <a className='font-benzin'>DESIGN</a>
              </li>
            </ul>
          </nav>
          <div>
            <h1 className='capitalize m-3 text-3xl font-benzin dark:text-sky-600 text-slate-800 text-center'></h1>
            <div className='grid lg:grid-cols-6 md:grid-cols-4 sm:grid-cols-2 gap-4'>
            </div>            
          </div>
          <div>
          </div>
        </section>
      </main>
    </div>
  )
}
