/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react'
import getToken from './api/spotifyAPI.js'
import Image from 'next/image.js'

export default function Home() {
  
  const [ darkMode, setDarkmode] = useState(true);
  
  //getToken.execute();

  return (
    <div className={darkMode ? "dark" : "light"}>
      <Head>
        <title>BLKKDOUT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='dark:bg-slate-900 text-slate-800 bg-no-repeat px-10'> 
        <section className='min-h-screen backdrop-blur-3xl'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-2xl font-benzin dark:text-white text-slate-800'>BLKKDOUT</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkmode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/></li>
            </ul>
          </nav>
          <div>
            <h1 className='capitalize m-3 text-3xl font-benzin dark:text-sky-600 text-slate-800 text-center'>LATEST RELEASES</h1>
            <div className='grid lg:grid-cols-6 md:grid-cols-4 sm:grid-cols-2 gap-4'>
            </div>            
          </div>
          <div>
          </div>
        </section>
      </main>
    </div>
  )
}
